name: learn git hub action
on: 
  push:
    branches: [main]
jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run: npm install
    - run: npm run build
    
    
    
  
  
    
